---
title: "07_functions"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(ggplot2)
library(DT)
```

# Functions Tutorial

## Setup Some Test Data

```{r load-data}

airtemps <- c(212, 78.3, 30, 32)

celsius1 <- (airtemps[1]-32)*5/9
celsius2 <- (airtemps[2]-32)*5/9
celsius3 <- (airtemps[3]-32)*5/9
celsius4 <- (airtemps[4]-32)*5/9
```


```{r create-function}

fahr_to_celsius <- function(fahr) {
  celsius <- (fahr-32)*5/9
  return(celsius)
}

(celsius5 <- fahr_to_celsius(airtemps[1]))
celsius1 == celsius5

```


```{r vectorized}

(cels_vect <- fahr_to_celsius(airtemps))

```


```{r celsius-to-fahr}

celsius_to_fahr <- function(celsius) {
  fahr <- (celsius*9/5 + 32)
  return(fahr)
}

```

```{r implement-func2}


celsius_to_fahr(airtemps)

```

```{r function-from-list}

convert_temps <- function(fahr) {
  celsius <- (fahr-32)*5/9
  kelvin <- celsius + 273.15
  return(list(fahr=fahr, celsius=celsius, kelvin=kelvin))
}

temps_df <- data.frame(convert_temps(seq(-100,100,10)))

```


```{r table-temps, echo=FALSE}

library(DT)

DT::datatable(temps_df)

```

```{r ggplot-cust}

custom_theme <- function(base_size = 9) {
  ggplot2::theme(
    axis.ticks = ggplot2::element_blank(),
    text       = ggplot2::element_text(family = 'Helvetica', color = 'gray30', size = base_size),
    plot.title = ggplot2::element_text(size = ggplot2::rel(1.25), hjust = 0.5, face = 'bold'),
    panel.background = ggplot2::element_blank(),
    legend.position  = 'right',
    panel.border     = ggplot2::element_blank(),
    panel.grid.minor = ggplot2::element_blank(),
    panel.grid.major = ggplot2::element_line(colour = 'grey90', size = .25),
    legend.key       = ggplot2::element_rect(colour = NA, fill = NA),
    axis.line        = ggplot2::element_blank()
  )
}

library(ggplot2)

ggplot(temps_df, mapping=aes(x=fahr, y=celsius, color=kelvin)) +
  geom_point() +
  scale_color_viridis_c() +
  custom_theme(10)

```



# Packages

